language: java
jdk:
  - openjdk8

branches:
  only:
    - master
#travis CI 서버의 home
cache:
  directories:
    - 'HOME/.m2/repository'
    - $HOME/.gradle
script: "./gradlew clean build"

before_install:
  - chmod +x gradlew


before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy  *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/com-joon-book.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: com-joon-book
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deploy: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: com-joon-book
    key: com-joon-book.zip
    bundle_type: zip
    application: com-joon-book3
    depployment_group: com-joon-book
    region: ap-northeast-2
    wait-until-deploy: true


#CI실행완료 시 메일로 알람
notifications:
  email:
    recipients:
      - joonhwaan@gmail.com


